export const vehicleType = ['Car', 'Convertible', 'Truck', 'SUV', 'Van']
export const manufacturers = [
    'Acura',
    'Alfa Romeo',
    'Aston Martin',
    'Audi',
    'Bentley',
    'BMW',
    'Buick',
    'Cadillac',
    'Chevrolet',
    'Chrysler',
    'Dodge',
    'Ferrari',
    'FIAT',
    'Ford',
    'Freightliner',
    'Genesis',
    'GMC',
    'Honda',
    'Hyundai',
    'INFINITI',
    'Jaguar',
    'Jeep',
    'Kia',
    'Lamborghini',
    'Land Rover',
    'Lexus',
    'Lincoln',
    'Lotus',
    'Maserati',
    'MAZDA',
    'McLaren',
    'Mercedes-Benz',
    'MINI',
    'Mitsubishi',
    'Nissan',
    'Porsche',
    'Ram',
    'Rolls-Royce',
    'SAAB',
    'Smart',
    'Subaru',
    'Tesla',
    'Toyota',
    'Vauxhall',
    'Volkswagen',
    'Volvo',
]
export const modelYears = [
    '2022',
    '2021',
    '2020',
    '2019',
    '2018',
    '2017',
    '2016',
    '2015',
    '2014',
    '2013',
    '2012',
    '2011',
    '2010',
    'Before 2010',
]
export const colors = [
    'Aluminum',
    'Beige',
    'Black',
    'Blue',
    'Brown',
    'Bronze',
    'Claret',
    'Copper',
    'Cream',
    'Gold',
    'Gray',
    'Green',
    'Maroon',
    'Metallic',
    'Navy',
    'Orange',
    'Pink',
    'Purple',
    'Red',
    'Rose',
    'Rust',
    'Silver',
    'Tan',
    'Turquoise',
    'White',
    'Yellow',
]

export const reportNames = [
    'Sale By Color',
    'Sale By Vehicle Type',
    'Sale By Manufacturer',
    'Top Customer Gross Income',
    'Manufacturer Repair',
    'Monthly Sale',
    'Below Cost Sale',
    'Average Days In Inventory',
    'Parts Statistics',
]